name: Auto Assign PR

on:
  pull_request:
    types: [opened]

# 権限不足によるエラー回避
permissions:
  pull-requests: write
  contents: read

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to author
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: ${{ github.actor }}
